### PR TITLE
Strip excess spaces at end of text lines

### PR DESCRIPTION
**Pull request by beadsland**
Spaces are added to the ends of lines somewhere along the line in edoc/xmerl processing.

However, trailing spaces may already be present on some lines.  In these cases, markdown will see a line terminated with a double space and render as an (unintended) hard return.

Added function to reduce multi-space terminations to a single space, resolving issue.

### CODE REVIEW

**Comment by uwiger** [comment]
Thanks, but perhaps you could squash some commits? It would make it easier to see what the actual resulting change is. Now, I need to look at all individual commits to figure it out.

**Comment by beadsland** [comment]
Hi Ulf,

I'd be glad to, although I'm not sure what that would entail.  By "squash some commits", are you asking me to delete commits from the github repository altogether, or something else?

I'm surprised there isn't a way to compare the entire pull request to the current repository in one go.  :(  No diff by date?
- Beads

http://twitter.com/beadsland

-----Original Message-----

**Comment by uwiger** [comment]
I'm sure there is a nifty option to git diff. OTOH, squashing commits is reasonably straightforward. You simply do

`git rebase -i HEAD~10`

(for example, to do an interactive rebase of the 10 last commits)

The command comes with fairly good instructions. Otherwise, see e.g. http://www.silverwareconsulting.com/index.cfm/2010/6/6/Using-Git-Rebase-to-Squash-Commits

Of course, rebase changes history, so if you want to do this after you've pushed something, you need to force-push your squashed commits.

...anyway, `git diff HEAD~10 HEAD` also works, of course, once I've cloned your repos. :)

**Comment by uwiger** [comment]
If you fix that wrongly indented line (edown_layout.erl, line 181), I'll merge the pull request - no need to rebase.

**Comment by beadsland** [comment]
Good to know.  Thanks!

I'll remember same if I do another multi-commit update where a single commit would have done the job as well.

Thanks for creating edown, BTW!
- Beads

http://twitter.com/beadsland

-----Original Message-----

**Comment by beadsland** [comment]
Thanks, done.

http://twitter.com/beadsland

-----Original Message-----

**Pull request merged**
