### PR TITLE
Tweaks to generated markdown

### PR DESCRIPTION
**Pull request by seth**
Hi Ulf,

Not sure if you will care for all or some of these patches. I've only tested them on an `overview.edoc` in one of my projects where I've started to experiment with making use of edown. That said, I think they improve the generated markdown.
- Remove unused imports from merl_lib in edown_xmerl
- Generated github-style "fenced" code blocks instead of `<pre>` tags.
- Fix "close" of markdown headers, octothorpe counts should match
- Adjust newline behavior for generated markdown. I see there is an existing issue/PR for this and am unclear if what I've done somehow breaks some edge cases. To my eye, the generated markdown is easier to read and I think will be "correct" for github use (I put that in quotes b/c markdown is markdown).

### CODE REVIEW

**Comment by uwiger** [comment]
A repository I often use to test edown is https://github.com/vinoski/erlsha2

I noticed now that the current edown doesn't generate the erlsha2 docs correctly either, so some further changes are needed. I haven't yet determined whether your changes make it better or worse. ;-)

**Comment by seth** [comment]
Thanks, I will try to take a look at that repo as a test

**Comment by seth** [comment]
I've had a look at the results of `make edoc` in erlsha2 and see that there are some problems. I'm experimenting with a few fixes and will update this PR when I get a chance to clean it up.

**Comment by uwiger** [comment]
Much appreciated. I must say that Markdown is a very "interesting" markup language. :)

**Comment by seth** [comment]
Here's an improved approach. I think the results are an improvement for the erlsha2 repo as well as the README fiel that I was testing in opscode's stats_hero repo. Not what I would call elegant, but still addresses a few things:

Literal code blocks in edoc now translated to fenced blocks in markdown. This lets the markdown engine handle escaping of the block content.

Special handling for edoc function description (identified by pre_pre tag) to allow anchor tags to work but to escape other angle brackets.

**Comment by uwiger** [comment]
I'm sorry I haven't had time to look closer at this. Things have been fairly hectic lately. I will try to find some time soon.

**Comment by seth** [comment]
I _completely_ understand :) Glad to know it is somewhere on the queue.

**Pull request merged**
