### PR TITLE
Add line breaks before ordered and unordered lists.

### PR DESCRIPTION
**Pull request by beadsland**
Only substantive changes are lines 170 & 171.

### CODE REVIEW

**Comment by beadsland** [comment]
Preformatted text was being rendered without whitespace between lines when rendered as HTML.

Converted to markdown format (leading tab), and updated brstrip to respect this.

**Comment by uwiger** [comment]
Hmm, this pull request is still open. Forgive me for being a bit unresponsive and confused, but is there something that still needs pulling?

**Comment by norton** [comment]
I'm not able to understand the set of patches but I am (**) interested in the "Preformatted text was being rendered without whitespace between lines when rendered as HTML." changes in particular.

*\* Hmm ... but I'm puzzled because it now seems that GitHub has improved it's rendering of verbatim text blocks.

This verbatim text of this link below used to be displayed on my browser as a single line.

https://github.com/norton/lets#quick-start-recipe

I'm unsure if this used to be an issue of with my browser, markdown, edown, or asciiedoc.  Oh well.

**Comment by uwiger** [comment]
Well, some of those issues are annoyingly subtle. I can partly agree with
Richard O'Keefe's rants about Markdown - it holds many surprises when you
try to do something more clever than just straightforward text. :)

BR,
Ulf

2012/7/5 Joseph Wayne Norton <
reply@reply.github.com

**Comment by norton** [comment]
Just a follow up on my previous comment.

This verbatim text of this link below is now displayed (again) on my browser as a single line.

https://github.com/norton/lets#quick-start-recipe

More strangeness.

**Comment by uwiger** [comment]
@norton, are you still having problems, or can I close this issue?

**Comment by norton** [comment]
I'm not seeing any such strangeness now.  Thanks for asking.  Please close this issue.

**Comment by uwiger** [comment]
Ok, will do. Thanks.

**Pull request closed without merging**
